### ISSUE TITLE
Add explanation for shortcuts

### ISSUE THREAD

**Issue by autarc** [OpenTechSchool/js-beginners-1#14]
On the [second day](http://opentechschool.github.io/js-beginners-day2/page4.html) are some snippets which uses the short version `i++` for incremental, as well as for `!` for negotiation. As these are quite common - they should be added to the initial explanation on the first day.

**Comment by jdennes** [comment]
I've [addressed](https://github.com/OpenTechSchool/js-beginners-day2/commit/5d599e90fe4fa0e41bce21b05daff38c4516f899#L2R398) the part about using `!` for negation when we first introduce the NOT operator on day two.

I guess there should just be an explanation of using `++` when people first see it too.

**Comment by xMartin** [comment]
We're removing the coupling of day 1 / day 2 so probably not so important any more.
