### ISSUE TITLE
What are the parameters in the smiley squadron exercise for?

### ISSUE THREAD

**Issue by xMartin** [OpenTechSchool/js-beginners-1#20]
The task with the smileySquadron asks learners to use x and y as parameters. I think this is confusing, at least I don't get why. As I understand it the function will contain the loop and change internal variables only. Maybe it's about defining a starting point but that could be just left out for simplicity.

**Comment by gabeno** [comment]
@xMartin I totally agree it is confusing. It is unnecessary to ask learners to use x and y as parameters for `smileySquadron()`. The parameters are already called by `smiley()` which in turn is within a loop. As the loop is initialized and executed, these internal variables are adjusted accordingly to draw smileys as desired.
