### ISSUE TITLE
Deleting/Merging old repos

### ISSUE THREAD

**Issue by finnp** [OpenTechSchool/js-beginners-1#26]
Hey everyone,

so I thought after the last workshop in Berlin, we would remove those two repos: [day1](https://github.com/OpenTechSchool/js-beginners-day1) and [day2](https://github.com/OpenTechSchool/js-beginners-day2) (or mark them as outdated or something).

Can someone do that and maybe rename this repo to just `js-beginners-workshop`?

Best,
Finn

PS: Okay renaming would maybe be a bad idea, since it would break links to the materials for GitHub pages. I am also still not sure where all the materials are located. But you know what I mean...

**Comment by xMartin** [comment]
How about renaming this one (js-beginners-4h-workshop) to js-beginners-1 and creating a new one with the old name of this one here that just points to the renamed one. Same with js-beginners-day2 -> js-beginners-2. Additionally add BIG deprecated warnings to js-beginners-day2

**Comment by xMartin** [comment]
Comments?
@OpenTechSchool/jscoaches

**Comment by finnp** [comment]
Yes I think that's a good idea.

**Comment by xMartin** [comment]
Done. Also create a pull request on learn.opentechschool.org https://github.com/OpenTechSchool/learn.opentechschool.org/pull/9
