### ISSUE TITLE
Add the missing step in Page 2 under Function exercise

### ISSUE THREAD

**Issue by akarsh** [OpenTechSchool/js-beginners-1#40]
A step missing in the [**Function exercise** from js-beginners -> page 2 ](https://github.com/OpenTechSchool/js-beginners-1/blob/gh-pages/page2.html#L247).

Where the `function smileySquadron()` has to be declared inside the `function drawing()`
Otherwise the render does not render it.

**Comment by xMartin** [comment]
I don't recall if many learners had issues with that. But a few lines above it is mentioned that the drawing function has to be touched in order to run other functions: https://github.com/OpenTechSchool/js-beginners-1/blob/gh-pages/page2.html#L215
